[user]
name = "Sean McKenna"
email = "mckennapsean@gmail.com"

[[--scope]]
--when.repositories = ["~/lucid"]
[--scope.user]
email = "seanm@lucidchart.com"

[ui]
default-command = "log"
editor = "hx"
pager = "delta"

[ui.diff]
formatter = "git"

[revset-aliases]
"changes()" = "mine() & mutable()"

[aliases]

# Find the closest ancestor with a bookmark pointing at it, and move it to the
# parent of the working copy.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

